---
title: "Figure 4 - this is how BFF/FFS works"
author: "Darach"
---

```{r,cache=F}
library(tidyverse)
library(stringr)
library(ggrepel)
library(Cairo)
load("../tmp/NameIDList.RData")
load("../tmp/dme209modelingDat.RData") 
load("../tmp/Figure4facs.RData")
load("../tmp/dme209_modelsToConsider.RData")
load("../tmp/dme209_filteredFits.RData")
load("../tmp/dme209_rankingList.RData")
```

```{r}
commonGAP1breaks <- c(.75,1.5,3,6,12,24,48)*1e3
cbPalette <- c("#56B4E9", "#009E73", "#D55E00", "#CC79A7","#E69F00", "#F0E442", "#0072B2" )
# scooped from CookBookR
```

```{r,cache=F}
procLabz4a <- function(x){
#  c(`pre-upshift`="Before upshift",shifted="10min after glutamine")[x]
  c(`pre-upshift`="Pre-shift",shifted="Post-shift")[x]
}
fig4flow <- flowDatar %>% 
  mutate(BiologicalReplicate=factor(BiologicalReplicate,levels=c("A","B","C","Pooled")))%>%
  ggplot()+theme_classic()+
    geom_vline(data=gatez,col="gray",aes(xintercept=UpperBound))+
    geom_vline(data=gatez,col="gray",aes(xintercept=LowerBound))+
    geom_hline(yintercept=0)+
    aes(x=APC.A)+
    stat_bin(aes(col=BiologicalReplicate),bins=100
      ,position="identity",alpha=0.80,geom="line")+
    stat_bin(aes(col=BiologicalReplicate),bins=100
      ,position="identity",alpha=0.80,geom="point",size=0.5)+
    guides(fill=F)+
    theme(axis.text.x=element_text(angle=90),legend.position="bottom"
      ,strip.text.y=element_text(size=10)
      ,text=element_text(size=10)
      )+
    facet_grid(Shifted~.,labeller=labeller(Shifted=procLabz4a)
      ,scales="free_y")+
    ylab("Events")+
    xlab(expression(paste(italic(GAP1)," mRNA FISH signal (a.u.)")))+
    scale_x_log10(breaks=commonGAP1breaks)+
    scale_color_manual("Biological Replicate",values=cbPalette)+
    coord_cartesian(xlim=c(700,5e4))
fig4flow
```

```{r,cache=F}
dme209pdat_spread <- modelingdat %>% 
  filter(Metric=="EstInput",FACSGate!="input") %>%
  dplyr::select(-Metric,-Signal,-PropSignal) %>%
  unite(Key,BiologicalReplicate,Shifted,MeanSignalInBin,FACSGate
    ,PCRreplicate,UpperBound,LowerBound) %>%
  spread(Key,PsuedoEvents,fill=0) %>%
  gather(Key,PsuedoEvents,-Strain,-Common) %>% 
  separate(Key,into=c("BiologicalReplicate","Shifted"
    ,"MeanSignalInBin","FACSGate","PCRreplicate"
    ,"UpperBound","LowerBound"),"_") %>% 
  dplyr::select(-PCRreplicate) 

dme209pdat <- dme209pdat_spread %>%
  group_by(Strain,Common,Shifted,BiologicalReplicate,FACSGate)%>%
#  nest(LowerBound,UpperBound,.key="gatez")%>%
  mutate(MeanPsuedoEvents=mean(PsuedoEvents,na.rm=T))%>%
  group_by(Strain,Common,Shifted,BiologicalReplicate)%>%
  mutate(NormMeanPsuedoEvents=MeanPsuedoEvents/sum(unique(MeanPsuedoEvents),na.rm=T))%>%
  ungroup()%>%
  mutate(Name=str_c(tolower(Common),"Δ")
    ,MeanSignalInBin=as.numeric(MeanSignalInBin))%>%
  distinct%>%arrange(Shifted)

fig4techRepsplotter <- function(toPlot=c("HIS3","GAP1","DAL80"),smoother=T) {
  z<-dme209pdat %>% 
    filter(Common%in%toPlot) %>%
    mutate(LabelName=str_c(Name,", ",Shifted)) %>%
    mutate(LabelName=factor(LabelName
        ,levels=unique(
          c(str_c(tolower(toPlot),"Δ, PreShift")
            ,str_c(tolower(toPlot),"Δ, Shifted")
            )
          )
        )
      )
  gatez <- z %>% dplyr::select(FACSGate,LabelName,UpperBound,LowerBound) %>%
    mutate(UpperBound=as.numeric(UpperBound)
      ,LowerBound=as.numeric(LowerBound))
  g<-z%>%
    ggplot()+theme_classic()+
    facet_wrap(~LabelName,dir="h",nrow=2,scales="free_y")+
    aes(x=MeanSignalInBin,y=PsuedoEvents,col=BiologicalReplicate)+
    scale_x_log10(breaks=commonGAP1breaks)+
    coord_cartesian(xlim=c(1000,19.2e3))+
    geom_vline(data=gatez,col="gray",aes(xintercept=UpperBound))+
    geom_vline(data=gatez,col="gray",aes(xintercept=LowerBound))+
    xlab(expression(paste(italic(GAP1)," mRNA FISH signal (a.u.)")))+
    scale_y_continuous(limits=c(0,NA))+
    ylab("Mutant strain abundance in bin\n( normalized mean psuedoevents)")+
    geom_hline(yintercept=0)+theme(axis.line.x=element_blank())+
    scale_color_manual(values=cbPalette)+
    guides(col=F)
  if (smoother) {
    return(g +
      stat_smooth(aes(group=Name),span=10,se=F,linetype="dashed",col="grey60")+
      geom_point()
      )
  } else {
    return(g + geom_point() )
  }
}
fig4techReps <- fig4techRepsplotter(c("HIS3","GAP1","URE2"),smoother=F)
fig4techReps 

```

```{r}
boundslist <- modelingdat %>% 
  dplyr::select(Shifted,FACSGate,LowerBound,UpperBound) %>%
  distinct%>%filter(FACSGate!="input")%>%
  mutate(GateIndex=c(p2=1,p3=2,p4=3,p5=4
    ,p6=1,p7=2,p8=3,p9=4)[as.character(FACSGate)]
    ) %>% 
  group_by(Shifted,GateIndex)%>%
  summarize(BoundsVector=list(
      c(LowerBound=LowerBound,UpperBound=UpperBound)
      )
    ) %>%
  group_by(Shifted) %>%
  arrange(GateIndex)%>%
  summarize(GateList=list(BoundsVector)) %>%
  ungroup()%>%
  summarize(ShiftList=list(setNames(GateList,nm=Shifted))) %>%
  pull(ShiftList) %>% unlist(recursive=F)

pintervalNormal <- function(gate,bounds,fitparm1,fitparm2) {
  return(
    pnorm(log(bounds[["UpperBound"]])
      ,mean=fitparm1,sd=fitparm2
      ) 
    -
    pnorm(log(bounds[["LowerBound"]])
      ,mean=fitparm1,sd=fitparm2
      ) 
    )
}

fig4modelFitsplotter <- function(toPlot=c("DAL80","GZF3","URE2","GAT1")) {
  z<-dme209pdat %>% 
    dplyr::select(-PsuedoEvents)%>%distinct%>%
    filter(Common%in%toPlot) %>%
    group_by(Strain,Common,Shifted,FACSGate,Name)%>%
    mutate(MeanMeanPsuedoEvents=mean(MeanPsuedoEvents)
      ,MeanMeanSignalInBin=mean(MeanSignalInBin))%>%
    group_by(Strain,Common,Shifted,Name)%>%
    mutate(NormMeanMeanPsuedoEvents=MeanMeanPsuedoEvents/sum(unique(MeanMeanPsuedoEvents)))%>%
    mutate(LabelName=str_c(Name,", ",ifelse(Shifted=="Shifted","post-shift","pre-shift"))) %>%
    mutate(LabelName=str_replace(LabelName,"Δ,","Δ,\n"))%>%
    mutate(LabelName=factor(LabelName
        ,levels=unique(
          c(str_c(tolower(toPlot),"Δ,\n pre-shift")
            ,str_c(tolower(toPlot),"Δ,\n post-shift")
      ))))%>%
    arrange(LabelName)%>%
    mutate(LabelName=ifelse(grepl("his3",as.character(LabelName))
        ,str_replace(as.character(LabelName),"his3Δ","wild-type"),as.character(LabelName)))%>%
    ungroup()%>%
    mutate(LabelName=factor(LabelName,levels=unique(LabelName)))%>%
    left_join(
      modelsToConsider%>%
        filter(BiologicalReplicate=="Pooled")%>%
        dplyr::select(Strain,Shifted,LogMiddle,LogSpread)
      ,by=c("Strain","Shifted")
      )%>%
    group_by(Strain,Shifted,FACSGate)%>%
    mutate(
      GateIndex=recode(FACSGate,p2=1,p3=2,p4=3,p5=4,p6=1,p7=2,p8=3,p9=4)
      ,sketch=list(data.frame(
          x=log(mean(MeanSignalInBin))
          ,y=pintervalNormal(NULL
            ,boundslist[Shifted][[1]][GateIndex][[1]]
            ,LogMiddle,LogSpread)
          )
        )
      )
  gatez <- z %>% dplyr::select(FACSGate,LabelName,UpperBound,LowerBound) %>%
    mutate(UpperBound=as.numeric(UpperBound)
      ,LowerBound=as.numeric(LowerBound))
  g<-z%>%
    ggplot()+theme_classic()+
    facet_wrap(~LabelName,dir="h",nrow=2,scales="free_y")+
    aes(x=MeanSignalInBin,y=NormMeanPsuedoEvents,col=BiologicalReplicate)+
    scale_x_log10(breaks=commonGAP1breaks)+
    coord_cartesian(xlim=c(1000,19.2e3))+
    geom_vline(data=gatez,col="gray",aes(xintercept=UpperBound))+
    geom_vline(data=gatez,col="gray",aes(xintercept=LowerBound))+
    xlab(expression(paste(italic(GAP1)," mRNA FISH signal (a.u.)")))+
    scale_y_continuous(limits=c(0,NA))+
    ylab("Mutant strain abundance in bin\n(normalized mean psuedoevents)")+
    geom_hline(yintercept=0)+
    theme(axis.line.x=element_blank()
      ,axis.text.x=element_text(angle=90)
      ,strip.text=element_text(size=10)
      ,text=element_text(size=10))+
    guides(col=F)+
    scale_color_manual(values=cbPalette)+
    geom_point(data=z%>%unnest,aes(x=exp(x),y=y),col="black",shape=16,size=2.5)+
    geom_line(data=z%>%unnest,aes(x=exp(x),y=y),col="black",linetype="dashed")+
    geom_point() 
}
#fig4modelFits <- fig4modelFitsplotter(c("GAT1","SLG1","LSM1"))
#fig4modelFits <- fig4modelFitsplotter(c("GAT1","GZF3","DAL80"))
fig4modelFits <- fig4modelFitsplotter(c("HIS3","GAP1","DAL80","GAT1"))
fig4modelFits

```


```{r,fig4dsupp}
filteredFits <- filteredFits %>% 
  mutate(LabelName=str_c(tolower(Common),"Δ"))

#procLabzParmDist <- function(x){
#  c(`PreShift:FALSE`="Before upshift,\neach replicate"
#    ,`PreShift:TRUE`="Before upshift,\npooled replicates"
#    ,`Shifted:FALSE`="10min after,\neach replicate"
#    ,`Shifted:TRUE`="10min after,\npooled replicates"
#    )[x]
#}
procLabzParmDist <- function(x){
  c(`PreShift`="Pre-shift"
    ,`Shifted`="Post-shift"
    )[x]
}

fig4parmDist <- left_join(filteredFits%>%dplyr::select(Strain,Shifted)
    ,modelsToConsider
    ,by=c("Strain","Shifted")
    ) %>% 
  mutate(Shifted=relevel(factor(Shifted),"PreShift"))%>%
  filter(BiologicalReplicate!="Pooled")%>%
  mutate(Facetting=factor(Shifted))%>%
#  mutate(Facetting=factor(Shifted):factor(BiologicalReplicate=="Pooled"))%>%
#  mutate(BiologicalReplicate=factor(BiologicalReplicate,levels=c("A","B","C","Pooled")))%>%
  ggplot()+theme_classic()+
  facet_grid(Facetting~.
    ,labeller=labeller(Facetting=procLabzParmDist)
    ,scales="free_y")+
  theme(legend.position="top",axis.text.x=element_text(angle=90)
    ,strip.text.y=element_text(size=10)
    ,text=element_text(size=10)
    )+
  aes(x=exp(LogMiddle))+
  ylab("Counts")+
  xlab(expression(paste("Mean ",italic(GAP1)," expression, modeled (a.u.)")))+
  scale_x_log10(breaks=commonGAP1breaks)+
  geom_hline(yintercept=0)+
  scale_color_manual(values=cbPalette)+
  coord_cartesian(xlim=c(700,50e3))+
  stat_bin(aes(col=BiologicalReplicate),bins=100
    ,position="identity",alpha=0.80,geom="line")+
  stat_bin(aes(col=BiologicalReplicate),bins=100
    ,position="identity",alpha=0.80,geom="point",size=0.5)
fig4parmDist

fig4sup <- cowplot::plot_grid(fig4flow,fig4parmDist,labels=c("A","B")
  ,align="v",axis="lr",ncol=1,rel_heights=c(.4,.6))
fig4sup
```

```{r}

fig4prezi <- cowplot::plot_grid(fig4flow+guides(col=F),fig4parmDist
  ,align="v",axis="lr",ncol=1,rel_heights=c(.4,.6))
fig4prezi
```

```{r,actual4d}
filteredFits <- filteredFits %>% 
  mutate(LabelName=str_c(tolower(Common),"Δ"))

gbaser <- filteredFits %>% 
  mutate(Shifted=relevel(factor(Shifted),"PreShift"))%>%
  ggplot()+theme_classic()+
  aes(x=Shifted,y=exp(LogMiddle))+
  scale_y_log10(breaks=commonGAP1breaks)+
  xlab(expression(paste("Mean ",italic(GAP1)," expression, modeled (a.u.)")))+
  geom_violin(adjust=0.2)+
  xlab(NULL)+
  scale_x_discrete(labels=c(PreShift="Pre-shift",
      Shifted="Post-shift")
#  scale_x_discrete(labels=c(PreShift="Before\nglutamine upshift",
#      Shifted="10 min after\nglutamine upshift")
    )+
  theme(legend.position="bottom")+
#  scale_color_manual(values=c(cbPalette[1:3],"#000000"))+
  scale_color_manual(values=c( `No expression`="#E69F00"
      ,`Wild-type`="#000000" ,`Transcription\nactivator`="#0072B2"
      ,`Transcription\nrepressor`="#EE0000"))
gbaser

gbase <- filteredFits %>% 
  mutate(Shifted=relevel(factor(Shifted),"Shifted"))%>%
  ggplot()+theme_classic()+
  aes(x=Shifted,y=exp(LogMiddle))+
  scale_y_log10(breaks=commonGAP1breaks)+
  ylab(expression(paste("Mean ",italic(GAP1)," expression, modeled (a.u.)")))+
  geom_violin(adjust=0.2)+
  xlab(NULL)+
  scale_x_discrete(labels=c(PreShift="Pre-shift",
      Shifted="Post-shift")
#  scale_x_discrete(labels=c(PreShift="Before\nglutamine upshift",
#      Shifted="10 min after\nglutamine upshift")
    )+
  theme(legend.position="bottom",text=element_text(size=10))+
#  scale_color_manual(values=c(cbPalette[1:3],"#000000"))+
  scale_color_manual(values=c( `No expression`="#E69F00"
      ,`Wild-type`="#000000" ,`Transcription\nactivator`="#0072B2"
      ,`Transcription\nrepressor`="#EE0000"))+coord_flip()
gbase

thispdat <- filteredFits %>%
  filter(Common%in%c("HIS3","GAP1","DAL80","GZF3","URE2","GAT1"
#      ,"LSM1","LSM6","PAT1"
      )
    )%>%
  mutate(Class=NA)%>%
  mutate(Class=ifelse(grepl("HIS3",Common),"Wild-type",Class))%>%
  mutate(LabelName=ifelse(grepl("HIS3",Common),"Wild-type",LabelName))%>%
  mutate(Class=ifelse(grepl("GAP1",Common),"No expression",Class))%>%
  mutate(Class=ifelse(grepl("(DAL80)|(GZF3)|(URE2)",Common)
      ,"Transcription\nrepressor",Class)
    )%>%
  mutate(Class=ifelse(grepl("GAT1",Common),"Transcription\nactivator",Class))%>%
  mutate(Class=ifelse(grepl("(LSM1)|(LSM6)|(PAT1)",Common)
      ,"P-body\ncomponent",Class)
    ) 
fig4violinNCR <- gbase+
  geom_line(data=thispdat%>%dplyr::select(Shifted,Strain,LogMiddle,Class)%>%distinct
    ,aes(col=Class,group=Strain))+
  geom_point(data=thispdat%>%dplyr::select(Shifted,LogMiddle,Class)%>%distinct
    ,aes(col=Class))+
  geom_text_repel(data=thispdat%>%filter(Shifted=="PreShift")%>%
      dplyr::select(Shifted,LogMiddle,LabelName)%>%distinct
    ,aes(label=LabelName),nudge_x=1.0,segment.color="grey50"
    ,label.padding=0.25,box.padding=0.25,direction="both"
    ,min.segment.length=0,force=10,seed=1234,max.iter=5000
    ,xlim=c(2.5,4.0),ylim=log10(c(1000,10000))
    ,angle=0)+
  guides(col=guide_legend(title="",ncol=2))+
  coord_flip(xlim=c(1,3.5))
fig4violinNCR
fig4 <- cowplot::plot_grid(
  cowplot::plot_grid(fig4flow+guides(col=F)
      ,fig4parmDist+guides(col=guide_legend(title="Biological Replicate"))
    ,labels=c("A","C")
    ,rel_heights=c(0.45,0.55)
    ,align="v",axis="lr"
    ,ncol=1
    )
  ,cowplot::plot_grid(fig4modelFits+theme(axis.text.y=element_blank())
    ,fig4violinNCR
    ,labels=c("B","D")
    ,vjust=1.5
    ,rel_heights=c(0.5,0.5)
    ,ncol=1
    )
  ,ncol=2)
fig4
ggsave("../output/Figure4.un.tiff",fig4,width=7.5,height=6)

```


```{r}

prezi_violin_his3gap1 <- gbaser+
  geom_point(data= thispdat%>%filter(grepl("(HIS3)|(GAP1)",Common))%>%
      dplyr::select(Shifted,LogMiddle,Class)%>%distinct 
    ,aes(col=Class))+
  geom_line(data=thispdat%>%filter(grepl("(HIS3)|(GAP1)",Common))%>%
      dplyr::select(Shifted,Strain,LogMiddle,Class)%>%distinct
    ,aes(col=Class,group=Strain))+
  geom_text_repel(data=thispdat%>%filter(grepl("(HIS3)|(GAP1)",Common))%>%
      filter(Shifted=="PreShift")%>%
      dplyr::select(Shifted,LogMiddle,LabelName)%>%distinct
    ,aes(label=LabelName),nudge_x=-0.3,nudge_y=0.0,segment.color="grey50") 

prezi_violin_ncr <- gbaser+
  geom_point(data= thispdat%>%filter(!grepl("(HIS3)|(GAP1)",Common))%>%
      dplyr::select(Shifted,LogMiddle,Class)%>%distinct 
    ,aes(col=Class))+
  geom_line(data=thispdat%>%filter(!grepl("(HIS3)|(GAP1)",Common))%>%
      dplyr::select(Shifted,Strain,LogMiddle,Class)%>%distinct
    ,aes(col=Class,group=Strain))+
  geom_text_repel(data=thispdat%>%filter(!grepl("(HIS3)|(GAP1)",Common))%>%
      filter(Shifted=="PreShift")%>%
      dplyr::select(Shifted,LogMiddle,LabelName)%>%distinct
    ,aes(label=LabelName),nudge_x=-0.3,nudge_y=0.0,segment.color="grey50") 


modelz <- fig4modelFitsplotter(c("HIS3","GAP1","DAL80"))

toPlot <- c("HIS3","GAP1","DAL80")
  z<-dme209pdat %>% 
    dplyr::select(-PsuedoEvents)%>%distinct%>%
    filter(Common%in%toPlot) %>%
    group_by(Strain,Common,Shifted,FACSGate,Name)%>%
    mutate(MeanMeanPsuedoEvents=mean(MeanPsuedoEvents)
      ,MeanMeanSignalInBin=mean(MeanSignalInBin))%>%
    group_by(Strain,Common,Shifted,Name)%>%
    mutate(NormMeanMeanPsuedoEvents=MeanMeanPsuedoEvents/sum(unique(MeanMeanPsuedoEvents)))%>%
    mutate(LabelName=str_c(Name,", ",ifelse(Shifted=="Shifted","post-shift","pre-shift"))) %>%
    mutate(LabelName=factor(LabelName
        ,levels=unique(
          c(str_c(tolower(toPlot),"Δ, pre-shift")
            ,str_c(tolower(toPlot),"Δ, post-shift")
            )
          )
        )
      )%>%
    left_join(
      modelsToConsider%>%
        filter(BiologicalReplicate=="Pooled")%>%
        dplyr::select(Strain,Shifted,LogMiddle,LogSpread)
      ,by=c("Strain","Shifted")
      )%>%
    group_by(Strain,Shifted,FACSGate)%>%
    mutate(
      GateIndex=recode(FACSGate,p2=1,p3=2,p4=3,p5=4,p6=1,p7=2,p8=3,p9=4)
      ,sketch=list(data.frame(
          x=log(mean(MeanSignalInBin))
          ,y=pintervalNormal(NULL
            ,boundslist[Shifted][[1]][GateIndex][[1]]
            ,LogMiddle,LogSpread)
          )
        )
      )
  gatez <- z %>% dplyr::select(FACSGate,LabelName,UpperBound,LowerBound) %>%
    mutate(UpperBound=as.numeric(UpperBound)
      ,LowerBound=as.numeric(LowerBound))
  g<-z%>%
    ggplot()+theme_classic()+
    facet_wrap(~LabelName,dir="h",nrow=2,scales="free_y")+
    aes(x=MeanSignalInBin,y=NormMeanPsuedoEvents,col=BiologicalReplicate)+
    scale_x_log10(breaks=commonGAP1breaks)+
    coord_cartesian(xlim=c(1000,19.2e3))+
    geom_vline(data=gatez,col="gray",aes(xintercept=UpperBound))+
    geom_vline(data=gatez,col="gray",aes(xintercept=LowerBound))+
    xlab(expression(paste(italic(GAP1)," FISH signal (a.u.)")))+
    scale_y_continuous(limits=c(0,NA))+
    ylab("Mutant strain abundance in bin\n( normalized mean psuedoevents)")+
    geom_hline(yintercept=0)+
    theme(axis.line.x=element_blank()
      ,axis.text.x=element_text(angle=90))+
    guides(col=F)+
    scale_color_manual(values=cbPalette)+
    geom_point() 
g
g+geom_point(data=z%>%unnest,aes(x=exp(x),y=y),col="black",shape=16,size=2.5)+
  geom_line(data=z%>%unnest,aes(x=exp(x),y=y),col="black",linetype="dashed")

```


```{r}
sessionInfo()
```



